### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by ezekg** [keygen-sh/keygen-api#716]
Related to #644. Looking at GitHub Actions since we're already using GitHub. We should use a matrix for `CE`/`EE` and `singleplayer`/`multiplayer` tests. For example, we could do something like this:

```yml
name: API
on:
  push:
    branches: [master]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        edition:
          - CE
          - EE
        mode:
          - singleplayer
          - multiplayer
    env:
      KEYGEN_EDITION: ${{matrix.edition}}
      KEYGEN_MODE: ${{matrix.mode}}
    steps:
      - run: rake test
```
