### ISSUE TITLE
Add Docker Compose support

### ISSUE THREAD

**Issue by Menelion** [keygen-sh/keygen-api#727]
I'm considering adding Keygen to our small business. I've just read the self-host documentation and, although the solution is based on Docker, there is no mention of how to make an optimal setup with Docker Compose. I.e., you have to have Postgres, Redis and stuff outside Docker or separately add those containers on your own.  
Would be nice to have a Compose example if you at Keygen use it yourselves.

**Comment by MylesWritesCode** [comment]
I'm also wondering this. This is the [closest I got](https://github.com/keygen-sh/community/discussions/77), but I'm still working through setting it up in a dev environment. It requires you allowing `tty` in your compose and using `docker compose exec` to first set it up, then to re-run the docker compose with a changed command.

**Comment by ezekg** [comment]
I'm fine with an option to bypass the setup Rake task entirely. Bypassing the setup sounds like it'd work nicely for docker-compose. I'm thinking maybe add the account and admin creation to `db/seeds.rb` in the case the `KEYGEN_ACCOUNT_ID`, `KEYGEN_ADMIN_EMAIL` and `KEYGEN_ADMIN_PASSWORD` environment variables are set.

Something like this in `db/seeds.rb` may work?

```ruby
# file: db/seeds.rb
# ...

if ENV.key?('KEYGEN_ACCOUNT_ID') && ENV.key?('KEYGEN_ADMIN_EMAIL') && ENV.key?('KEYGEN_ADMIN_PASSWORD')
  id = ENV.fetch('KEYGEN_ACCOUNT_ID')
  
  Account.find_or_create_by!(id:) do |account|
    email    = ENV.fetch('KEYGEN_ADMIN_EMAIL')
    password = ENV.fetch('KEYGEN_ADMIN_PASSWORD')
    
    account.assign_attributes(
      billing_attributes: { state: 'subscribed' },
      users_attributes: [{ email:, password: }],
      plan_attributes: { name: 'Ent 0', price: 1 },
      protected: true,
    )
  end
end
```

Since `rails db:seed` needs to be run regardless to seed event types and permissions, I think that's a decent solution.

**Comment by vivekpd15** [comment]
Any plans to get this in @ezekg? We want to host this on Kubernetes and automated setup would be extremely helpful.

**Comment by ezekg** [comment]
No official plans, but open to a PR.

**Comment by khronii** [comment]
Initial setup: (make sure to comment out web/worker section)
```
docker compose up -d
docker run --rm -it \
  --net keygen-net \
  -e SECRET_KEY_BASE="$(openssl rand -hex 64)" \
  -e ENCRYPTION_DETERMINISTIC_KEY="$(openssl rand -base64 32)" \
  -e ENCRYPTION_PRIMARY_KEY="$(openssl rand -base64 32)" \
  -e ENCRYPTION_KEY_DERIVATION_SALT="$(openssl rand -base64 32)" \
  -e DATABASE_URL="postgres://postgres:postgres@keygen-postgres:5432/postgres" \
  -e REDIS_URL="redis://keygen-redis:6379" \
  -e KEYGEN_HOST="api.keygen.localhost" \
  -e KEYGEN_MODE="singleplayer" \
  -e KEYGEN_EDITION="EE" \
  keygen/api setup
```

The output might be something like:
```
...
To complete setup, run the following in a shell, or add it to a shell profile:
  export SECRET_KEY_BASE=foo
  export ENCRYPTION_DETERMINISTIC_KEY=bar
  export ENCRYPTION_PRIMARY_KEY=baz
  export ENCRYPTION_KEY_DERIVATION_SALT=salty
  export KEYGEN_EDITION=CE
  export KEYGEN_MODE=singleplayer
  export KEYGEN_ACCOUNT_ID=account-id-gibberish
  export KEYGEN_HOST=domain.example.com
...
```
Make sure to copy it all (without "export ") into .config/keygen.env

.env
```
KEYGEN_WEB_PORT=3000
```

.config/keygen.env (Put those EXPORTs and other environment variables in here)
```
SECRET_KEY_BASE=...
ENCRYPTION_DETERMINISTIC_KEY=...
ENCRYPTION_PRIMARY_KEY=...
ENCRYPTION_KEY_DERIVATION_SALT=...
KEYGEN_EDITION=...
KEYGEN_MODE=...
KEYGEN_ACCOUNT_ID=...
KEYGEN_HOST=domain.example.com

DATABASE_URL=postgres://postgres:postgres@keygen-postgres:5432/postgres
REDIS_URL=redis://keygen-redis:6379
```

docker-compose.yml
```
version: "3"

services:
  ##Uncomment the following after initial setup & restart
  #worker:
  #  image: "keygen/api"
  #  command: worker
  #  container_name: keygen-worker
  #  restart: unless-stopped
  #  depends_on:
  #    - db
  #    - redis
  #  networks:
  #    - keygen-net
  #  env_file:
  #    - .config/keygen.env
  #  volumes:
  #    - ./keygen:/etc/keygen
  #web:
  #  image: "keygen/api"
  #  command: web
  #  container_name: keygen-web
  #  restart: unless-stopped
  #  depends_on:
  #    - db
  #    - redis
  #  ports:
  #    - "${KEYGEN_WEB_PORT}:3000"
  #  networks:
  #    - keygen-net
  #  env_file:
  #    - .config/keygen.env
  #  volumes:
  #    - ./keygen:/etc/keygen
  redis:
    image: redis
    restart: unless-stopped
    container_name: keygen-redis
    networks:
      - keygen-net
    volumes:
      - ./redis:/data
  db:
    image: postgres
    restart: unless-stopped
    container_name: keygen-postgres
    networks:
      - keygen-net
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  keygen-net:
```

**Comment by MShrimp4** [comment]
(Reposted since I used the wrong github account)

Copy .env and docker-compose.yml from below and run this command.
Initial setup: (make sure to comment out web/worker section)
```
docker compose up -d
docker run --rm -it \
  --net keygen-net \
  -e SECRET_KEY_BASE="$(openssl rand -hex 64)" \
  -e ENCRYPTION_DETERMINISTIC_KEY="$(openssl rand -base64 32)" \
  -e ENCRYPTION_PRIMARY_KEY="$(openssl rand -base64 32)" \
  -e ENCRYPTION_KEY_DERIVATION_SALT="$(openssl rand -base64 32)" \
  -e DATABASE_URL="postgres://postgres:postgres@keygen-postgres:5432/postgres" \
  -e REDIS_URL="redis://keygen-redis:6379" \
  -e KEYGEN_HOST="api.keygen.localhost" \
  -e KEYGEN_MODE="singleplayer" \
  -e KEYGEN_EDITION="EE" \
  keygen/api setup
```

The output might be something like:
```
...
To complete setup, run the following in a shell, or add it to a shell profile:
  export SECRET_KEY_BASE=foo
  export ENCRYPTION_DETERMINISTIC_KEY=bar
  export ENCRYPTION_PRIMARY_KEY=baz
  export ENCRYPTION_KEY_DERIVATION_SALT=salty
  export KEYGEN_EDITION=CE
  export KEYGEN_MODE=singleplayer
  export KEYGEN_ACCOUNT_ID=account-id-gibberish
  export KEYGEN_HOST=domain.example.com
...
```
Make sure to copy it all (without "export ") into .config/keygen.env, and uncomment web/worker section from docker-compose.yml and re-run.

.env
```
KEYGEN_WEB_PORT=3000
```

.config/keygen.env (Put those EXPORTs and other environment variables in here)
```
SECRET_KEY_BASE=...
ENCRYPTION_DETERMINISTIC_KEY=...
ENCRYPTION_PRIMARY_KEY=...
ENCRYPTION_KEY_DERIVATION_SALT=...
KEYGEN_EDITION=...
KEYGEN_MODE=...
KEYGEN_ACCOUNT_ID=...
KEYGEN_HOST=domain.example.com

DATABASE_URL=postgres://postgres:postgres@keygen-postgres:5432/postgres
REDIS_URL=redis://keygen-redis:6379
```

docker-compose.yml
```
version: "3"

services:
  ##Uncomment the following after initial setup & restart
  #worker:
  #  image: "keygen/api"
  #  command: worker
  #  container_name: keygen-worker
  #  restart: unless-stopped
  #  depends_on:
  #    - db
  #    - redis
  #  networks:
  #    - keygen-net
  #  env_file:
  #    - .config/keygen.env
  #  volumes:
  #    - ./keygen:/etc/keygen
  #web:
  #  image: "keygen/api"
  #  command: web
  #  container_name: keygen-web
  #  restart: unless-stopped
  #  depends_on:
  #    - db
  #    - redis
  #  ports:
  #    - "${KEYGEN_WEB_PORT}:3000"
  #  networks:
  #    - keygen-net
  #  env_file:
  #    - .config/keygen.env
  #  volumes:
  #    - ./keygen:/etc/keygen
  redis:
    image: redis
    restart: unless-stopped
    container_name: keygen-redis
    networks:
      - keygen-net
    volumes:
      - ./redis:/data
  db:
    image: postgres
    restart: unless-stopped
    container_name: keygen-postgres
    networks:
      - keygen-net
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  keygen-net:
```
